name: guime
description: "Guime App"
publish_to: "none"
version: 1.0.1+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_compass:
  permission_handler:
  camera:

  cupertino_icons:
  lottie:
  google_maps_flutter:
  geolocator:
  flutter_launcher_icons:
  shared_preferences:
  freezed_annotation:
  intl:
  rive:
  camera_avfoundation:
  flutter_riverpod:
  hooks_riverpod:
  riverpod_annotation:
  flutter_hooks:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  riverpod_generator:
  freezed:

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/lottie/guime_title.json
    - assets/images/
    - assets/riv/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFCDCD"
  adaptive_icon_foreground: "assets/images/app_icon.png"
